name: Publish Package to npmjs
on:
  release:
    types: [published]

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # only want to run this job on the repo and not on forks.
    if: github.repository_owner == 'BolajiOlajide'

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"
          registry-url: https://registry.npmjs.org
          scope: "@bolajiolajide"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Build
        run: |
          pnpm run build

      - uses: simenandre/publish-with-pnpm@v2
        with:
          npm-auth-token: ${{ secrets.NPM_ACCESS_TOKEN }}
