name: Publish Package to npmjs
on:
  release:
    types: [published]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@bolajiolajide"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: |
          echo "@username:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" >> .npmrc
      - name: Publish 🚀
        shell: bash
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
